"""new migration

Revision ID: 1fc7be47037e
Revises: 
Create Date: 2025-11-21 03:45:39.076234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc7be47037e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('single', 'multiple', 'ranked', name='polltype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'closed', name='pollstatus'), nullable=False),
    sa.Column('allow_anonymous', sa.Boolean(), nullable=True),
    sa.Column('allow_change_vote', sa.Boolean(), nullable=True),
    sa.Column('max_choices', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poll_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_options')
    op.drop_table('polls')
    # ### end Alembic commands ###
